{% set version = "0.9" %}

package:
  name: patchelf
  version: {{ version }}

source:
  fn: patchelf-{{ version }}.tar.gz
  url: http://nixos.org/releases/patchelf/patchelf-{{ version }}/patchelf-{{ version }}.tar.gz
  sha256: f2aa40a6148cb3b0ca807a1bf836b081793e55ec9e5540a5356d800132be7e0a

build:
  number: 2
  skip: true  # [not linux]

test:
  commands:
    - patchelf --help

about:
  home: http://nixos.org/patchelf.html
  license: GPL 3
  license_file: COPYING
  summary: A small utility to modify the dynamic linker and RPATH of ELF executables.

extra:
  recipe-maintainers:
    - jakirkham
    - mjuric
