schema_version: 1

context:
  version: 0.18.0

package:
  name: patchelf
  version: ${{ version }}

source:
  url: https://github.com/NixOS/patchelf/releases/download/${{ version }}/patchelf-${{ version }}.tar.bz2
  sha256: 1952b2a782ba576279c211ee942e341748fdb44997f704dd53def46cd055470b

build:
  number: 2
  skip: win
  dynamic_linking:
    binary_relocation: false

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - make
    - gnuconfig

tests:
  - script:
      - bash -c '[[ "$(patchelf --version)" =~ "patchelf ${{ version }}".* ]]'

about:
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: A small utility to modify the dynamic linker and RPATH of ELF executables.
  description: |
    PatchELF is a small utility to modify the dynamic linker and RPATH of ELF
    executables.
  homepage: http://nixos.org/patchelf.html
  repository: https://github.com/NixOS/patchelf
  documentation: http://nixos.org/patchelf.html

extra:
  recipe-maintainers:
    - jakirkham
    - leofang
    - mjuric
    - xhochy
